import { task } from "hardhat/config"
import { verifyCeremony } from "./contracts"
import { initializeUserServices } from "../../test/utils"

task("verifyCeremony", "A task that can be used to verify a ceremony finalization validity")
    .addPositionalParam("ceremonyPrefix")
    .addPositionalParam("outputDirectory")
    .addPositionalParam("solidityVersion")
    .addPositionalParam("wasmPath")
    .addPositionalParam("circuitInputs")
    .addPositionalParam("verifierTemplatePath")
    .addPositionalParam("coordinatorUID")
    .setAction(async (taskArgs, hre) => {
        // get a signer
        const [deployer] = await hre.ethers.getSigners()

        // init user app
        const { userFirestore, userFunctions } = initializeUserServices()

        // verify ceremony
        await verifyCeremony(
            userFunctions,
            userFirestore,
            taskArgs.ceremonyPrefix,
            taskArgs.outputDirectory,
            taskArgs.solidityVersion,
            taskArgs.wasmPath,
            taskArgs.circuitInputs,
            taskArgs.verifierTemplatePath,
            deployer,
            taskArgs.coordinatorUID
        )

        // if we are here it is because it didn't throw so we can safely assume that it all was veriifer
        console.log(`[+] The artifacts generated by the ceremony ${taskArgs.ceremonyPrefix} are valid`)
    })
