name: Deploy to Staging

on:
  pull_request:
    branches: staging
  push:
    branches: staging

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish-cli-package:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/publish-staging-packages.yaml

  deploy-staging:
    uses: ./.github/workflows/firebase-deploy-staging.yaml
    secrets: inherit
    with:
      environment: staging
      branch: ${{ github.ref }}
      firebase_project: ${{ vars.FIREBASE_PROJECT_STAGING }}
